name: cloud_firestore_web
description: The web implementation of cloud_firestore
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web
version: 0.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirestoreWeb
        fileName: firestore_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase: ^7.0.0
  http_parser: ^3.1.3
  meta: ^1.1.7
  cloud_firestore_platform_interface:
    path: ../cloud_firestore_platform_interface
  js: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore:
    path: ../cloud_firestore
  firebase_core_platform_interface: ^1.0.0
  firebase_core_web: ^0.1.1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"

